modLoader = "kotlinforforge"
loaderVersion = "[${versions.kotlin_neoforge_range},)"
license = "${mod_license}"

[[mods]]
modId = "testmod"
version = "${mod_version}"
displayName = "TestMod"
authors = "${mod_authors}"
description = '''TestMod for KLib'''

[[dependencies.testmod]]
modId = "neoforge"
type = "required"
versionRange = "[${versions.neoforge_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.testmod]]
modId = "minecraft"
type = "required"
versionRange = "[${versions.minecraft}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.testmod]]
modId = "kotlinforforge"
type = "required"
versionRange = "[${versions.kotlin_neoforge_range},)"
ordering = "NONE"
side = "BOTH"